[package]
name = "Planet"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "https://github.com/unitn-ap-2025/common.git", version = "0.1.0" }
crossbeam-channel = "0.5.15"
env_logger = "0.11.8"
log = "0.4.29"
